[theme]
# Primary accent color for interactive elements.
primaryColor = "#E694FF"

# Background color for the main content area.
backgroundColor = "#000305"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FF5733"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "Arial"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false
css = ["./static/style.css"]